version: "3.2"
services:
  php:
    container_name: php-service
    build: './php/'
    volumes:
      - ./public_html/:/var/www/html/
  apache:
    container_name: apache_service
    build: './apache/'
    ports:
      - "8080:80"
    volumes:
      - ./public_html/:/var/www/html/